# Generated by Django 3.2 on 2022-09-16 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=50)),
                ('broker_name', models.CharField(max_length=50)),
                ('total_amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '계좌',
                'verbose_name_plural': '계좌',
            },
        ),
        migrations.CreateModel(
            name='StockGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('group_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '종목 정보',
                'verbose_name_plural': '종목 정보',
            },
        ),
        migrations.CreateModel(
            name='AccountInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account', to='investment.account')),
                ('isin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StockGroup', to='investment.stockgroup')),
            ],
            options={
                'verbose_name': '계좌 투자 정보',
                'verbose_name_plural': '계좌 투자 정보',
            },
        ),
    ]
