# Generated by Django 3.2 on 2022-09-21 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=50)),
                ('brokerage', models.CharField(max_length=50)),
                ('invest_amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '계좌',
                'verbose_name_plural': '계좌',
            },
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=50)),
                ('asset_name', models.CharField(max_length=50)),
                ('group_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '자산 그룹 정보',
                'verbose_name_plural': '자산 그룹 정보',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('transfer_amount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '입금 거래 정보',
                'verbose_name_plural': '입금 거래 정보',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='investment.account')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.assetgroup')),
            ],
            options={
                'verbose_name': '계좌 자산 정보',
                'verbose_name_plural': '계좌 자산 정보',
            },
        ),
    ]
