# Generated by Django 3.2 on 2022-09-17 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='account_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='investment.account'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='isin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_info', to='investment.assetgroup'),
        ),
    ]
