# Generated by Django 3.2 on 2022-09-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='total_amount',
            new_name='invest_amount',
        ),
    ]
