# Generated by Django 3.2 on 2022-09-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_rename_total_amount_account_invest_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('transfer_amount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '입금 거래 정보',
                'verbose_name_plural': '입금 거래 정보',
            },
        ),
    ]
